### ISSUE TITLE
webapp2 3rd release

### ISSUE THREAD

**Issue by mymtwcom** [GoogleCloudPlatform/webapp2#119]
Will be good to see middleware support in webapp2 3rd version. Without of it, I think 3rd release does not make sense, from users/developers side.
And updated docs website like here too needed I think http://docs.readthedocs.io/en/latest/install.html

**Comment by jonparrott** [comment]
3.0.0 release is really meant to mark the new maintainers and the first time the package has been published since 2012, any additional features are just for funsies.

Since we could add middleware in a backwards-compatible fashion, 3.1.0 would be fine.

What would this support look like? Since webapp2 is a WSGI framework, any existing WSGI middleware should just work.

**Comment by mymtwcom** [comment]
ok, sorry I didn't know that wsgi middleware will work here, what do u think about 
"updated docs website like here too needed I think http://docs.readthedocs.io/en/latest/install.html"
in 3rd release?

**Comment by jonparrott** [comment]
Absolutely. Happy to review any PRs to update docs.
